#!/usr/bin/env bash
# PostToolUse(Edit|Write|MultiEdit): format and fix the ONE file that was just edited.
#
# Never the package, never the repository. A whole-project format run triggered by a
# one-line edit has previously touched unrelated files and required a revert — and the
# damage is invisible in the moment, because the tool reports success and the diff only
# grows later.
#
# Which formatter runs is discovered from configuration that is present, per the rule in
# `engineering-paved-path:project-commands`: read what the repository actually declares,
# never assume the popular tool. If nothing resolves, this exits silently. A formatter
# invented on the spot would reformat a file to a style the repository does not use, which
# is worse than leaving it alone.
#
# Always exits 0. A PostToolUse hook that fails a turn over a formatting nicety is a hook
# that gets removed; the edit has already happened, and nothing here is a gate.
set -uo pipefail

[ "${HOOK_SKIP_LINT_FIX:-}" = "1" ] && exit 0

command -v jq >/dev/null 2>&1 || exit 0
payload=$(cat)
file=$(printf '%s' "$payload" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || exit 0
[ -n "$file" ] && [ -f "$file" ] || exit 0

# Hook input is untrusted: the path is passed as a single argv element, never interpolated
# into a command string.
case "$file" in
  */node_modules/*|*/dist/*|*/build/*|*/out/*|*/.next/*|*/coverage/*|*/vendor/*|*/target/*) exit 0 ;;
  *.min.*|*-lock.json|*.lock) exit 0 ;;
esac

# A generated file is not yours to reformat, whatever its extension says.
head -n 5 -- "$file" 2>/dev/null | grep -qiE '@generated|Code generated by|DO NOT EDIT' && exit 0

# The root is resolved from the FILE, never from the working directory. Falling back to
# $PWD points the config lookup at whatever project the session happens to be sitting in,
# which is how a file gets formatted to an unrelated repository's rules.
dir=$(cd "$(dirname -- "$file")" && pwd)
root=$(git -C "$dir" rev-parse --show-toplevel 2>/dev/null || true)
if [ -z "$root" ]; then
  candidate="$dir"
  while [ "$candidate" != "/" ]; do
    for marker in package.json pnpm-lock.yaml yarn.lock package-lock.json bun.lock bun.lockb \
                  pyproject.toml Cargo.toml go.mod composer.json Gemfile; do
      [ -f "$candidate/$marker" ] && { root="$candidate"; break 2; }
    done
    candidate=$(dirname -- "$candidate")
  done
fi
[ -n "$root" ] || root="$dir"

runner=()                                       # how this repository runs a local binary
if   [ -f "$root/pnpm-lock.yaml" ];    then runner=(pnpm exec)
elif [ -f "$root/yarn.lock" ];         then runner=(yarn)
elif [ -f "$root/bun.lockb" ] || [ -f "$root/bun.lock" ]; then runner=(bun x)
elif [ -f "$root/package-lock.json" ]; then runner=(npx --no-install)
fi

# A formatter that hangs must not hang the turn. The wrapper is built once here and
# applied to the BINARY inside run(), not around run() itself: `timeout` is an external
# command and cannot execute a shell function, so wrapping the function meant that every
# machine with coreutils — every Linux box — ran no formatter at all and exited 0 saying
# nothing. Absent (a stock macOS), the array is empty and the binary is called directly.
tmo=()
command -v timeout >/dev/null 2>&1 && tmo=(timeout 20)

run() { # run a tool, preferring the project-local install, and never install anything
  local tool="$1"; shift
  # The .bin shim IS the local install — execute it directly. Going through the package
  # runner resolves the package rather than the shim, and fails where only the shim is
  # present, which is exactly the case this branch is trying to serve.
  if [ -x "$root/node_modules/.bin/$tool" ]; then
    ${tmo[@]+"${tmo[@]}"} "$root/node_modules/.bin/$tool" "$@" >/dev/null 2>&1 || true
    return 0
  fi
  if [ ${#runner[@]} -gt 0 ] && [ -d "$root/node_modules/$tool" ]; then
    ${tmo[@]+"${tmo[@]}"} "${runner[@]}" "$tool" "$@" >/dev/null 2>&1 || true
    return 0
  fi
  command -v "$tool" >/dev/null 2>&1 || return 1
  ${tmo[@]+"${tmo[@]}"} "$tool" "$@" >/dev/null 2>&1 || true
}

case "$file" in
  *.ts|*.tsx|*.js|*.jsx|*.mjs|*.cjs|*.mts|*.cts|*.vue|*.svelte|*.json|*.css|*.scss|*.md)
    if   [ -f "$root/biome.json" ] || [ -f "$root/biome.jsonc" ]; then
      run biome check --write -- "$file"
    else
      # ESLint and Prettier are separate decisions: a repository may have either.
      for config in eslint.config.js eslint.config.mjs eslint.config.cjs eslint.config.ts .eslintrc .eslintrc.js .eslintrc.cjs .eslintrc.json .eslintrc.yml; do
        [ -f "$root/$config" ] && { run eslint --fix -- "$file"; break; }
      done
      for config in .prettierrc .prettierrc.json .prettierrc.js .prettierrc.cjs .prettierrc.yml .prettierrc.yaml prettier.config.js prettier.config.mjs prettier.config.cjs; do
        [ -f "$root/$config" ] && { run prettier --write -- "$file"; break; }
      done
    fi
    ;;
  *.py)
    if [ -f "$root/ruff.toml" ] || [ -f "$root/.ruff.toml" ] || grep -qs '\[tool\.ruff' "$root/pyproject.toml"; then
      run ruff check --fix -- "$file"
      run ruff format -- "$file"
    elif grep -qs '\[tool\.black' "$root/pyproject.toml"; then
      run black -q -- "$file"
    fi
    ;;
  *.rs)
    [ -f "$root/Cargo.toml" ] && run rustfmt -- "$file"
    ;;
  *.go)
    [ -f "$root/go.mod" ] && run gofmt -w -- "$file"
    ;;
esac

exit 0
